language: ruby
sudo: required

env:
  global:
    secure: UQEVLPeTl6NG7X2y3mdXKEOtchx/uPNNwWOckOAaKfFNIG3MMqfDMnBYGrcj38303zwbqYxjg/2ptwpTeA+eW1TWe1N+I1Y/BX6jA0bUKZgS2PvQXN8SHehDV33pWkSkhxhAi3pp/T3cvVugse2MMWtlRCZ9WizY0jn1viU40G3VQJYi4cNe+QwdxEvG7/GlWW11i9D8ev4nhTKEwYUGQ/KZHjCZwWzVjVesvV7mfcvjZWN4OrMYMH76hjIqA6WIa2pVtIgLp1ZF6g13AYQPlqzBTsItssukQfh/1fzrdGD9v/fbH60N6NDqpJmqVfDnCHOuioS8ZNPo9GZ62nDeTPa5EWETwLxqcbJWL4xWZFvDHSEUL5ZFLfEXZAANw2jPojYZU71mqRSGeLE+ZVh2sb11t4oOis0do7MR8G9/3U7vcqpoigslSaECtXN2G3lA4gAJkKzbkvfnQtseDF6LTclG29mGmA8g6uXNN9kBCK5alkhrrerad1otDfkp/09mwWNGzjSlBYGhrbHZiHVNnVlHr0dMbOc33xxOzqSeFNZsUYnUbGt01pVQzIgzMp5cErEHdxMmwvLoePNcaT2iy5kseJOkKlheDF6Lmbo/yoCta7MCIi0Fdrz7AYL+LnYEW8cHKx5vnu7R3/gkDjGdCIG0WRQ+HZPDD19maq6sem0=

jobs:
  include:
    - stage: "Semantic Release"
      name: "Generate a new release and changelogs"
      language: node_js
      node_js: lts/*
      os:
        - linux
      install:
        - npm install
      script: skip
      deploy:
        provider: script
        api_key: "$GITHUB_TOKEN"
        node_js: lts/*
        skip_cleanup: true
        script: npx semantic-release
        on:
          branch: master

    - stage: "GitHub Release"
      name: "Send the generated files to the new GitHub release"
      services:
        - docker
      env:
        - COMPOSE_FILE=docker-compose.yml
      script:
        - TRAVIS_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        - git shortlog -s | cut -f 2- > book/contributors.txt
        - docker-compose run --rm ebook $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: "$GITHUB_TOKEN"
        file_glob: true
        file: book-release/*
        skip_cleanup: true
        on:
          branch: master
